/**
 * @file This file previously contained dummy LoRaWAN receiver simulation.
 * 
 * REMOVED: All dummy data generators have been removed.
 * The system now uses live ThingSpeak data exclusively.
 *
 * For live sensor data, the system uses:
 * - Python processor: thingspeak_live_processor.py
 * - AI model: DRQN neural network with live predictions
 * - Data storage: live_sensor_data.json (updated every 5 seconds)
 * 
 * No simulated or dummy data is generated by this service anymore.
 */
'use server';

import type { CrashData } from '@/lib/types';

/**
 * This function now returns an error since dummy data has been removed.
 * Use the ThingSpeak live data system instead.
 *
 * @deprecated Use live ThingSpeak data via /api/live-sensor-data
 * @returns {Promise<CrashData>} Throws error - dummy data removed
 */
export async function getSensorData(): Promise<CrashData> {
  throw new Error(
    'Dummy sensor data has been removed. System now uses live ThingSpeak data exclusively. ' +
    'Access live data via /api/live-sensor-data endpoint or Python continuous monitor.'
  );
}
