#!/usr/bin/env python3
"""
CrashGuard Integration Script
This script can be called from Node.js to send actual emails
"""

import sys
import json
import os
from test_email import CrashGuardEmail
import datetime


def send_crash_alert_from_nodejs(crash_data_json):
    """
    Send crash alert email based on data from Node.js application
    Expected JSON format:
    {
        "location": "GPS coordinates or address",
        "severity": "Low/Medium/High", 
        "speed": 75,
        "recipient": "email@example.com",
        "timestamp": "ISO date string"
    }
    """
    try:
        # Parse the JSON data
        crash_data = json.loads(crash_data_json)
        
        # Extract data
        location = crash_data.get('location', 'Unknown Location')
        severity = crash_data.get('severity', 'Unknown')
        speed = crash_data.get('speed', 0)
        recipient = crash_data.get('recipient', 'mritulashankar@gmail.com')
        timestamp = crash_data.get('timestamp', datetime.datetime.now().isoformat())
        
        # Create email system
        email_system = CrashGuardEmail(source=0)
        
        # Connect to email server
        if not email_system.email_conn():
            # If connection fails, return simulation success
            print("PYTHON EMAIL SIMULATION:")
            print(f"   FROM: crashguard1234@gmail.com")
            print(f"   TO: {recipient}")
            print(f"   SUBJECT: Emergency Crash Alert - {severity}")
            print(f"   LOCATION: {location}")
            print(f"   SPEED: {speed} km/h")
            print(f"   TIME: {timestamp}")
            print("   STATUS: Simulated (authentication failed)")
            
            return {
                "success": True, 
                "message": f"Email simulated to {recipient} (auth failed)",
                "reference_code": "VCD-SIM123"
            }
        
        # Generate reference code
        import random
        import string
        vcd_reference_code = "VCD" + ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
        
        # Create professional crash alert message
        crash_message = f"""CRITICAL VEHICLE CRASH DETECTED

A vehicle crash has been detected by the CrashGuard monitoring system and requires immediate response.

INCIDENT DETAILS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Location: {location}
Severity Level: {severity}
Impact Speed: {speed} km/h
Detection Time: {timestamp}
Reference Code: {vcd_reference_code}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EMERGENCY RESPONSE ACTIONS:
• Verify safety of vehicle occupants immediately
• Contact emergency services if medical assistance is required
• High-impact collision detected by advanced sensor systems
• Follow established emergency response protocols

IMPORTANT: This alert was automatically generated by the CrashGuard 
vehicle safety monitoring system. Please respond according to your 
emergency protocols and contact emergency services if needed.
"""
        
        # Send the email
        success = email_system.send_email(
            send_message=crash_message,
            location=location,
            mail=recipient,
            vcd_reference_code=vcd_reference_code
        )
        
        # Close connection
        email_system.quit_conn()
        
        if success:
            return {
                "success": True, 
                "message": f"Crash alert sent to {recipient}",
                "reference_code": vcd_reference_code
            }
        else:
            return {"success": False, "error": "Failed to send email"}
            
    except Exception as e:
        # Return detailed error information
        error_msg = f"Python integration error: {str(e)}"
        print(f"ERROR: {error_msg}")
        return {"success": False, "error": error_msg}


def main():
    """Main function to handle command line usage"""
    try:
        if len(sys.argv) < 2:
            # Default test if no arguments provided
            print("CrashGuard Integration Script")
            print("Testing with default crash data...")
            
            test_data = {
                "location": "Highway 101, Mile Marker 23",
                "severity": "High",
                "speed": 85,
                "recipient": "mritulashankar@gmail.com",
                "timestamp": datetime.datetime.now().isoformat()
            }
            
            result = send_crash_alert_from_nodejs(json.dumps(test_data))
            print(json.dumps(result, indent=2))
            
        else:
            # Handle input from Node.js - check if temp file path provided
            if len(sys.argv) >= 3 and sys.argv[1] == '--temp-file':
                # Read from temp file (new method)
                temp_file_path = sys.argv[2]
                try:
                    # Try different encodings to handle Windows file encoding issues
                    encodings_to_try = ['utf-8', 'utf-16', 'utf-16-le', 'utf-8-sig']
                    crash_data_json = None
                    
                    for encoding in encodings_to_try:
                        try:
                            with open(temp_file_path, 'r', encoding=encoding) as f:
                                crash_data_json = f.read().strip()
                            print(f"Successfully read file with {encoding} encoding", file=sys.stderr)
                            break
                        except UnicodeDecodeError:
                            continue
                    
                    if crash_data_json is None:
                        raise Exception("Could not read file with any supported encoding")
                    
                    # Clean up temp file
                    os.remove(temp_file_path)
                    print(f"Read data from temp file: {temp_file_path}", file=sys.stderr)
                except Exception as file_error:
                    print(f"Error reading temp file: {file_error}", file=sys.stderr)
                    result = {"success": False, "error": f"Temp file error: {str(file_error)}"}
                    print(json.dumps(result))
                    return
            else:
                # Original command line method (fallback)
                crash_data_json = sys.argv[1]
                
                # Debug: Print what we received (but limit length for security)
                print(f"Received data length: {len(crash_data_json)} characters", file=sys.stderr)
                if crash_data_json.startswith('{') and crash_data_json.endswith('}'):
                    print("Data appears to be valid JSON format", file=sys.stderr)
                else:
                    print(f"Data doesn't look like JSON: {crash_data_json[:50]}...", file=sys.stderr)
            
            result = send_crash_alert_from_nodejs(crash_data_json)
            print(json.dumps(result))
            
    except Exception as e:
        error_result = {"success": False, "error": f"Main execution error: {str(e)}"}
        print(json.dumps(error_result))


if __name__ == "__main__":
    main()
